services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - task-management

networks:
  task-management:
    external: true
